BikeRentalWebApp/Areas/Roles/Controllers/RoleController.cs
using BikeRentalWebApp.Areas.Roles.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BikeRentalWebApp.Areas.Roles.Controllers
{
   
    public class RoleController : Controller
    {
        public RoleManager<Role> RM { get; set; }
        public RoleController(RoleManager<Role> _manager)
        {
            RM = _manager;

        }

        [Area("Roles")]

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult List()
        {


            return View(RM.Roles.ToList());
        }
        [Area("Roles")]
        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Area("Roles")]
        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult Edit(string id)
        {

            var RoleToEdit = RM.Roles.FirstOrDefault(r => r.Id == id);

            return View(RoleToEdit);
        }
        [Area("Roles")]
        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult Delete(string id)
        {
            return View(RM.Roles.FirstOrDefault(r => r.Id == id));
        }
        [Area("Roles")]
        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult Details(string id)
        {

            return View(RM.Roles.FirstOrDefault(r => r.Id == id));
        }

        [Area("Roles")]
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Create(Role role)
        {
            if (role == null) return RedirectToAction("List");

            await RM.CreateAsync(role);

            return RedirectToAction("List");

        }
        [Area("Roles")]
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Edit(Role role)
        {
            await RM.UpdateAsync(role);
            return RedirectToAction("List");
        }
        [Area("Roles")]
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Delete(Role role)
        {
            await RM.DeleteAsync(role);
            return RedirectToAction("List");
        }


    }
}

BikeRentalWebApp/Areas/Users/Controllers/UserController.cs
using BikeRentalWebApp.Areas.Roles.Models;
using BikeRentalWebApp.Areas.Users.Models;
using BikeRentalWebApp.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BikeRentalWebApp.Areas.Users.Controllers
{
    [Area("Users")]
    public class UserController : Controller
    {
        public UserManager<User> UM { get; set; }
        public RoleManager<Role> RM { get; set; }
        public UserController(UserManager<User> _manager, RoleManager<Role> _Rmanager)
        {
            UM = _manager;
            RM = _Rmanager;
        }
        


        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult List()
        {


            return View(UM.Users.ToList());
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult Edit(string id)
        {

            var UserToEdit = UM.Users.FirstOrDefault(u => u.Id == id);

            return View(UserToEdit);
        }
        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult Delete(string id)
        {
            return View(UM.Users.FirstOrDefault(u => u.Id == id));
        }
        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public IActionResult Details(string id)
        {

            return View(UM.Users.FirstOrDefault(u => u.Id == id));
        }


        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            if (user == null)
            {
                Warning.warningMessage = "Użytkownik jest nullem";
                return RedirectToAction("List");
            }

            await UM.CreateAsync(user);

            return RedirectToAction("List");

        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Edit(User user, List<string> selectedRoles)
        {

            var _user = UM.Users.Where(u => u.UserName == user.UserName).FirstOrDefault();
            if(_user == null) { return RedirectToAction("List"); }
            _user.UserName = user.UserName;
            _user.Email = user.Email;
            _user.PasswordHash = user.PasswordHash;
            _user.PhoneNumber = user.PhoneNumber;
            await UM.UpdateAsync(_user);
            var AllRoles = RM.Roles.ToList();
            IEnumerable<string> rolesString = AllRoles.Select(r => r.Name).ToList()!;
            foreach (string role in rolesString)
            {
                await UM.RemoveFromRoleAsync(_user, role);

            }
            foreach (string role in selectedRoles)
            {
                await UM.AddToRoleAsync(_user, role);

            }
            var Roles = UM.GetRolesAsync(_user);
            return RedirectToAction("List");
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public async Task<IActionResult> Delete(User user)
        {
            await UM.DeleteAsync(user);
            return RedirectToAction("List");
        }
    }
}

BikeRentalWebApp/Controllers/RentalPointsController.cs
using AutoMapper;
using BikeRentalWebApp.Database.Repos;
using BikeRentalWebApp.Database.Repos.Entities;
using BikeRentalWebApp.Database.Validatior;
using BikeRentalWebApp.Models;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;

namespace BikeRentalWebApp.Controllers
{
    public class RentalPointsController : Controller
    {
        private Mapper mapper;
        private RentalPointValidator validator;
        public RentalPointsController()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<RentalPoint, RentalPointViewModel>());
            mapper = new Mapper(config);
            validator = new();
        }

        RentalPointsRepository repo = new();
        // GET: RentalPointsController
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {

            List<RentalPointViewModel> list = new();

            foreach (RentalPoint point in repo.GetAll())
            {
                RentalPointViewModel view = new();
                mapper.Map(point, view);
                list.Add(view);
            }
            Warning.warningMessage = "";
            return View(list);
        }
        // GET: RentalPointsController/Details/5
        public ActionResult Details(Guid id)
        {
            var details = repo.FindById(id);
            RentalPointViewModel detailsView = new();
            if (details != null)
            {

                mapper.Map(details, detailsView);
                return View(detailsView);

            }
            else
            {
                return Redirect(nameof(List));
            }

        }
        // GET: RentalPointsController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: RentalPointsController/Create
        [HttpPost]
        public ActionResult Create(string Miasto, string Ulica, string Numer)
        {
            try
            {
                //TODO: Popraw validacje danych
                int.TryParse(Numer, out var num);

                RentalPoint rental = new(Miasto, Ulica, num);
                ValidationResult result = validator.Validate(rental);
                if (result.IsValid)
                {
                    repo.Add(rental);
                    Warning.warningMessage = "";
                    return RedirectToAction(nameof(List));

                }
                else
                {
                    Warning.warningMessage = result.Errors.FirstOrDefault().ErrorMessage;
                    return RedirectToAction(nameof(Create));
                }
            }
            catch
            {
                return Redirect(nameof(List));
            }
        }

        // GET: RentalPointsController/Edit/5
        public ActionResult Edit(Guid id)
        {

            var toEdit = repo.FindById(id);
            RentalPointViewModel view = new();
            if (toEdit is not null)
            {
                mapper.Map(toEdit, view);

                return View(view);

            }
            else
            {
                return Redirect(nameof(List));
            }
        }

        // POST: RentalPointsController/Edit/5
        [HttpPost]
        public ActionResult Edit(Guid id, string Miasto, string Ulica, string Numer)
        {
            try
            {
                int.TryParse(Numer, out var num);
                var rental = new RentalPoint(id, Miasto, Ulica, num);
                var result = validator.Validate(rental);
                if (result.IsValid)
                {
                    repo.Edit(id, Miasto, Ulica, Numer);
                    Warning.warningMessage = "";
                }
                else
                {
                    Warning.warningMessage = result.Errors.FirstOrDefault().ErrorMessage;
                    return RedirectToAction(nameof(Edit));
                }


                return RedirectToAction(nameof(List));
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);

            }
        }

        // GET: RentalPointsController/Delete/5
        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            var toDelete = repo.FindById(id);
            if (toDelete is not null)
            {
                RentalPointViewModel view = new();
                mapper.Map(toDelete, view);
                return View(view);

            }
            else
            {
                return Redirect(nameof(List));
            }
        }

        // POST: RentalPointsController/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id, RentalPoint rental)
        {
            try
            {
                repo.Delete(repo.FindById(id));
                return RedirectToAction(nameof(List));
            }
            catch
            {
                return View();
            }
        }


    }
}

BikeRentalWebApp/Controllers/VechiclesController.cs
using AutoMapper;
using BikeRentalWebApp.Database.Repos;
using BikeRentalWebApp.Database.Repos.Entities;
using BikeRentalWebApp.Database.Validatior;
using BikeRentalWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BikeRentalWebApp.Controllers;

public class VechiclesController : Controller
{

    VechiclesRepository repo = new VechiclesRepository();

    private Mapper mapper;
    private Mapper mapperDetails;
    private VechicleValidator validator;
    public VechiclesController()
    {
        var config = new MapperConfiguration(cfg => cfg.CreateMap<Vechicle, VechicleViewModel>());
        var configDetails = new MapperConfiguration(cfg => cfg.CreateMap<Vechicle, VechicleDetailViewModel>());

        mapper = new Mapper(config);
        mapperDetails = new Mapper(configDetails);
        validator = new();
    }
    // GET
    public IActionResult List()
    {
        List<VechicleViewModel> list = new List<VechicleViewModel>();

        foreach (var vechicle in repo.GetAll())
        {
            VechicleViewModel view = new();
            mapper.Map(vechicle, view);
            list.Add(view);
        }
        Warning.warningMessage = "";
        return View(list);


    }

    public IActionResult Edit(Guid id)
    {
        var bike = repo.FindById(id);


        if (bike == null) return RedirectToAction("List");
        VechicleDetailViewModel view = new();
        mapperDetails.Map(bike, view);

        return View(view);
    }



    public IActionResult Details(Guid id)
    {
        var bike = repo.FindById(id);

        if (bike is null) return RedirectToAction("List");
        VechicleDetailViewModel view = new();

        mapperDetails.Map(bike, view);


        return View(view);
    }
    public IActionResult Delete(Guid id)
    {
        var bike = repo.FindById(id);

        if (bike is null) return RedirectToAction("List");
        else
        {

            VechicleViewModel view = new();
            mapper.Map(bike, view);
            return View(view);

        }
    }
    [HttpGet]
    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Edit(Guid id, string brand, string model, VechicleType type, decimal price, string image, string description)
    {
        var bikeToEdit = new Vechicle(id, brand, model, type, price, description, image);
        if (bikeToEdit == null) return RedirectToAction("List");
        var result = validator.Validate(bikeToEdit);
        if (result.IsValid)
        {
            try
            {

                repo.Edit(bikeToEdit);
                Warning.warningMessage = "";






                return RedirectToAction("List");
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

        }
        else
        {
            Warning.warningMessage = result.Errors.FirstOrDefault().ErrorMessage;
            return RedirectToAction("Edit");
        }


    }

    [HttpPost]
    public ActionResult Delete(Guid id, Vechicle vech)
    {
        try
        {

            repo.Delete(repo.FindById(id));

            return RedirectToAction(nameof(List));
        }
        catch (Exception e)
        {
            throw new Exception(e.Message);
        }

    }


    [HttpPost]
    public ActionResult Create(string Brand, string Model, VechicleType Type, decimal Price, string Description, string Image)
    {
        Vechicle vech = new(Brand, Model, Type, Price, Description, Image);
        var result = validator.Validate(vech);
        if (result.IsValid)
        {
            try
            {
                repo.Add(vech);
                Warning.warningMessage = "";

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }
        else
        {
            Warning.warningMessage = result.Errors.FirstOrDefault().ErrorMessage;
            return Redirect(nameof(Create));
        }

    }
}

BikeRentalWebApp/Views/Shared/_AdminLayout.cshtml
@{
}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" style="text-align:center;" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/Admin">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3" >Dashboard</div>
            </a>

            
            <!-- Sidebar - Users-->
            <a asp-area="Users" asp-action="List" asp-controller="User" class="btn btn-info" style="width:80%;margin-left:auto;margin-right:auto">
                <span class="text">Users</span>
            </a>

            <!-- Spacer -->
            <div style="height:10px;"></div>

            <!-- Sidebar - Roles-->
            <a asp-area="Roles" asp-action="List" asp-controller="Role" class="btn btn-info" style="width:80%;margin-left:auto;margin-right:auto">
                <span class="text">Roles</span>
            </a>
          
            






        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow" style="list-style:none;">

                    <!-- Sidebar Toggle (Topbar) -->
                    
                    <ul style="list-style:none;width:100%;">
                        <!-- Dasboard logo div -->
                        
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow" style="float:right;">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Witaj! @User.Identity.Name</span>
                                <img class="img-profile rounded-circle"
                                     src="~/img/undraw_profile.svg">
                            </a>
                        
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div id="main_content" style="height:90%; width:100%; scroll-behavior:auto;overflow:auto;">
                    @RenderBody()
                </div>
                <!-- End of Main Content -->
                <!-- Footer -->
                <footer class="bg-white" style="margin-bottom:0 !important;height:70px;line-height:35px;">
                    <div class="container" style="height:70px;">
                        <div class="copyright text-center" style="height:70px;">
                            <span>&copy; 2023 - BikeRentalWebApp <br /> <b>Contact:</b> | Email: jk058203@student.ath.edu.pl | Tel: 123 456 789</span>
                        </div>
                    </div>
                </footer>
                <!-- End of Footer -->

            </div>
            <!-- End of Content Wrapper -->

        </div>
        <!-- End of Page Wrapper -->
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

      

        <!-- Bootstrap core JavaScript-->
        <script src="~/vendor/jquery/jquery.min.js"></script>
        <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

        <!-- Core plugin JavaScript-->
        <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

        <!-- Custom scripts for all pages-->
        <script src="~/js/sb-admin-2.min.js"></script>

        <!-- Page level plugins -->
        <script src="~/vendor/chart.js/Chart.min.js"></script>

        <!-- Page level custom scripts -->
        <script src="~/js/demo/chart-area-demo.js"></script>
        <script src="~/js/demo/chart-pie-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>

</html>

BikeRentalWebApp/Views/Shared/_Layout.cshtml
@using BikeRentalWebApp.Areas.Users.Models;
@using Microsoft.AspNetCore.Html;
@using Microsoft.AspNetCore.Identity;

@inject UserManager<User> UM;

@{


    var _loggedInUsername = User?.Identity?.Name ?? "";
    var _user = UM.GetUserAsync(User ?? new System.Security.Claims.ClaimsPrincipal()).Result;
    List<string> UserRoles = new List<string>();
    if(_user is not null)
    {
         UserRoles = UM.GetRolesAsync(_user).Result.ToList();

    }
    
}




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] ATH Rental Vechicle App - @(_loggedInUsername != "" ? $" - {User?.Identity?.Name}" : "")</title>
    <!--Roboto Font-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <!--All links-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BikeRentalWebApp.styles.css" asp-append-version="true"/>
</head>
<body class="text-gray-400">
<header>
    <div class="logo align-middle">
            <h1 class="align-content-center"><a asp-controller="Home" asp-action="Index">Bike Rental Service - UBB</a> </h1>
    </div>
    <nav class="menu relative">
        <ul class="float-start">
                <li><a class="btn btn-dark  text-white btn-hoover-dark" asp-controller="Vechicles" asp-action="List">Vechicles</a></li>
                <li><a class="btn btn-dark  text-white btn-hoover-dark" asp-controller="RentalPoints" asp-action="List">Rental Points</a></li>
                <li><a class="btn btn-dark  text-white btn-hoover-dark" asp-controller="Home" asp-action="AboutUs">O nas</a></li>
                <li><a class="btn btn-dark  text-white btn-hoover-dark" asp-controller="Home" asp-action="Cooperation">Współpraca</a></li>
        </ul>
            <ul class="float-end accuont-menu-ul">

            
            <li>
                    @{

                        if (UserRoles.Contains("Administrator"))
                        {
                        <li><a class="btn btn-dark text-white btn-hoover-dark" href="/Admin">Admin dashboard</a></li> 
                        
                        }
                        

                        if(_loggedInUsername != "")
                        {
                        <li><a class="btn btn-dark  text-white btn-hoover-dark" asp-controller="Account" asp-action="Details">Konto</a></li>
                        <li><a class="btn btn-dark  text-white btn-hoover-dark" href="/Logout">Wyloguj</a></li>
                            
                                
                            
                        }else
                        {
                        <a class="btn btn-dark  text-white btn-hoover-dark" href="/Login"> Zaloguj</a>
                        <a class="btn btn-dark  text-white btn-hoover-dark" href="/Register"> Zarejestruj</a>
                        }
                    }
                   
                    
            </li>
        </ul>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - BikeRentalWebApp <br/> <b>Contact:</b> | Email: jk058203@student.ath.edu.pl | Tel: 123 456 789
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>